/**
 * Provider 厂商配置
 * 包含 130+ 主流模型厂商的详细配置信息
 */

import type {
  ProviderConfig,
  ProviderType,
  ProviderCategory,
} from "../../types/provider";

// ==================== 云服务商配置 ====================

const cloudProviders: ProviderConfig[] = [
  // ==================== 主流云服务商 ====================
  {
    type: "alibaba",
    name: "阿里云百炼",
    category: "cloud",
    icon: "☁️",
    description: "通义千问系列模型",
    website: "https://bailian.console.aliyun.com",
    docs: "https://help.aliyun.com/zh/model-studio",
    api: {
      defaultBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
      authType: "bearer",
      apiKeyPrefix: "sk-",
      apiKeyPlaceholder: "sk-...",
    },
    configFields: [],
    defaultModels: [
      {
        id: "qwen-max",
        name: "通义千问-Max",
        maxTokens: 32000,
        pricing: { input: 0.04, output: 0.12 },
        capabilities: { vision: true, streaming: true, functionCalling: true },
      },
      {
        id: "qwen-plus",
        name: "通义千问-Plus",
        maxTokens: 128000,
        pricing: { input: 0.0008, output: 0.002 },
        capabilities: { vision: true, streaming: true, functionCalling: true },
      },
      {
        id: "qwen-turbo",
        name: "通义千问-Turbo",
        maxTokens: 128000,
        pricing: { input: 0.0003, output: 0.0006 },
      },
      {
        id: "qwen-vl-max",
        name: "通义千问-VL-Max",
        maxTokens: 8192,
        pricing: { input: 0.02, output: 0.02 },
        capabilities: { vision: true, streaming: true },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "zhipu",
    name: "智谱 AI",
    category: "cloud",
    icon: "🔮",
    description: "GLM 系列大模型，支持长文本和多模态",
    website: "https://open.bigmodel.cn",
    docs: "https://open.bigmodel.cn/dev/api",
    api: {
      defaultBaseUrl: "https://open.bigmodel.cn/api/paas/v4",
      authType: "bearer",
      apiKeyPlaceholder: "智谱 API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "glm-4-plus",
        name: "GLM-4-Plus",
        maxTokens: 128000,
        pricing: { input: 0.05, output: 0.05 },
        capabilities: { vision: true, streaming: true, functionCalling: true },
      },
      {
        id: "glm-4-0520",
        name: "GLM-4-0520",
        maxTokens: 128000,
        pricing: { input: 0.1, output: 0.1 },
      },
      {
        id: "glm-4-air",
        name: "GLM-4-Air",
        maxTokens: 128000,
        pricing: { input: 0.001, output: 0.001 },
      },
      {
        id: "glm-4-flash",
        name: "GLM-4-Flash",
        maxTokens: 128000,
        pricing: { input: 0, output: 0 },
        capabilities: { vision: true, streaming: true },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "bytedance",
    name: "字节火山引擎",
    category: "cloud",
    icon: "🎵",
    description: "字节跳动豆包大模型",
    website: "https://www.volcengine.com/product/doubao",
    docs: "https://www.volcengine.com/docs/82379",
    api: {
      defaultBaseUrl: "https://ark.cn-beijing.volces.com/api/v3",
      authType: "bearer",
      apiKeyPlaceholder: "火山引擎 API Key",
    },
    configFields: [
      {
        key: "endpointId",
        label: "Endpoint ID",
        type: "text",
        required: true,
        description: "推理接入点 ID",
      },
    ],
    defaultModels: [
      {
        id: "doubao-pro-32k",
        name: "豆包 Pro 32K",
        maxTokens: 32768,
        pricing: { input: 0.0008, output: 0.002 },
      },
      {
        id: "doubao-lite-32k",
        name: "豆包 Lite 32K",
        maxTokens: 32768,
        pricing: { input: 0.0003, output: 0.0006 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "moonshot",
    name: "月之暗面",
    category: "cloud",
    icon: "🌙",
    description: "Kimi 大模型，超长上下文",
    website: "https://www.moonshot.cn",
    docs: "https://platform.moonshot.cn/docs",
    api: {
      defaultBaseUrl: "https://api.moonshot.cn/v1",
      authType: "bearer",
      apiKeyPrefix: "sk-",
      apiKeyPlaceholder: "sk-...",
    },
    configFields: [],
    defaultModels: [
      {
        id: "moonshot-v1-8k",
        name: "Moonshot V1 8K",
        maxTokens: 8192,
        pricing: { input: 0.012, output: 0.012 },
      },
      {
        id: "moonshot-v1-32k",
        name: "Moonshot V1 32K",
        maxTokens: 32768,
        pricing: { input: 0.024, output: 0.024 },
      },
      {
        id: "moonshot-v1-128k",
        name: "Moonshot V1 128K",
        maxTokens: 131072,
        pricing: { input: 0.06, output: 0.06 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "minimax",
    name: "MiniMax",
    category: "cloud",
    icon: "🎭",
    description: "MiniMax 大模型",
    website: "https://www.minimaxi.com",
    docs: "https://www.minimaxi.com/document",
    api: {
      defaultBaseUrl: "https://api.minimax.chat/v1",
      authType: "bearer",
      apiKeyPlaceholder: "MiniMax API Key",
    },
    configFields: [
      {
        key: "groupId",
        label: "Group ID",
        type: "text",
        required: true,
        description: "MiniMax Group ID",
      },
    ],
    defaultModels: [
      {
        id: "abab6.5s-chat",
        name: "ABAB 6.5s",
        maxTokens: 245760,
        pricing: { input: 0.001, output: 0.001 },
      },
      {
        id: "abab6.5g-chat",
        name: "ABAB 6.5g",
        maxTokens: 8192,
        pricing: { input: 0.003, output: 0.003 },
      },
      {
        id: "abab6.5t-chat",
        name: "ABAB 6.5t",
        maxTokens: 245760,
        pricing: { input: 0.015, output: 0.015 },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "siliconflow",
    name: "硅基流动 (SiliconFlow)",
    category: "cloud",
    icon: "🌊",
    description: "聚合 100+ 高性能大模型，支持 DeepSeek、Qwen 等",
    website: "https://cloud.siliconflow.cn",
    docs: "https://docs.siliconflow.cn",
    api: {
      defaultBaseUrl: "https://api.siliconflow.cn/v1",
      authType: "bearer",
      apiKeyPrefix: "sk-",
      apiKeyPlaceholder: "sk-...",
    },
    configFields: [],
    defaultModels: [
      {
        id: "deepseek-ai/DeepSeek-V3",
        name: "DeepSeek V3",
        maxTokens: 64000,
        pricing: { input: 0.0008, output: 0.0008 },
        capabilities: { vision: false, streaming: true, functionCalling: true },
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        maxTokens: 64000,
        pricing: { input: 0.001, output: 0.001 },
        capabilities: { vision: false, streaming: true, functionCalling: true },
      },
      {
        id: "Qwen/Qwen2.5-72B-Instruct",
        name: "Qwen 2.5 72B",
        maxTokens: 32768,
        pricing: { input: 0.001, output: 0.001 },
        capabilities: { streaming: true },
      },
      {
        id: "Qwen/Qwen2.5-32B-Instruct",
        name: "Qwen 2.5 32B",
        maxTokens: 32768,
        pricing: { input: 0.0005, output: 0.0005 },
        capabilities: { streaming: true },
      },
      {
        id: "meta-llama/Llama-3.3-70B-Instruct",
        name: "Llama 3.3 70B",
        maxTokens: 128000,
        pricing: { input: 0.0006, output: 0.0008 },
        capabilities: { streaming: true },
      },
      {
        id: "THUDM/glm-4-9b-chat",
        name: "GLM-4 9B",
        maxTokens: 128000,
        pricing: { input: 0.0001, output: 0.0001 },
        capabilities: { streaming: true },
      },
      {
        id: "deepseek-ai/DeepSeek-Coder-V2",
        name: "DeepSeek Coder V2",
        maxTokens: 64000,
        pricing: { input: 0.001, output: 0.001 },
        capabilities: { streaming: true },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  // ==================== 国内厂商 ====================
  {
    type: "baidu",
    name: "百度智能云",
    category: "cloud",
    icon: "🔵",
    description: "文心一言系列模型",
    website: "https://cloud.baidu.com",
    docs: "https://cloud.baidu.com/doc/WENXINWORKSHOP",
    api: {
      defaultBaseUrl:
        "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop",
      authType: "api_key",
      apiKeyPlaceholder: "百度 API Key",
    },
    configFields: [
      {
        key: "secretKey",
        label: "Secret Key",
        type: "password",
        required: true,
        description: "百度 Secret Key",
      },
    ],
    defaultModels: [
      {
        id: "ernie-4.0-8k",
        name: "文心一言 4.0",
        maxTokens: 8192,
        pricing: { input: 0.12, output: 0.12 },
      },
      {
        id: "ernie-3.5-8k",
        name: "文心一言 3.5",
        maxTokens: 8192,
        pricing: { input: 0.004, output: 0.008 },
      },
      {
        id: "ernie-speed-8k",
        name: "文心 Speed",
        maxTokens: 8192,
        pricing: { input: 0.001, output: 0.001 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "tencent",
    name: "腾讯混元",
    category: "cloud",
    icon: "🐧",
    description: "腾讯混元大模型",
    website: "https://cloud.tencent.com/product/hunyuan",
    docs: "https://cloud.tencent.com/document/product/1729",
    api: {
      defaultBaseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
      authType: "bearer",
      apiKeyPlaceholder: "腾讯 API Key",
    },
    configFields: [
      { key: "secretId", label: "Secret ID", type: "text", required: true },
      {
        key: "secretKey",
        label: "Secret Key",
        type: "password",
        required: true,
      },
    ],
    defaultModels: [
      {
        id: "hunyuan-lite",
        name: "混元 Lite",
        maxTokens: 256000,
        pricing: { input: 0, output: 0 },
      },
      {
        id: "hunyuan-standard",
        name: "混元 Standard",
        maxTokens: 32000,
        pricing: { input: 0.004, output: 0.008 },
      },
      {
        id: "hunyuan-pro",
        name: "混元 Pro",
        maxTokens: 32000,
        pricing: { input: 0.03, output: 0.06 },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "baichuan",
    name: "百川智能",
    category: "cloud",
    icon: "🌊",
    description: "百川大模型",
    website: "https://www.baichuan-ai.com",
    docs: "https://platform.baichuan-ai.com/docs",
    api: {
      defaultBaseUrl: "https://api.baichuan-ai.com/v1",
      authType: "bearer",
      apiKeyPlaceholder: "百川 API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "Baichuan4",
        name: "Baichuan 4",
        maxTokens: 128000,
        pricing: { input: 0.012, output: 0.012 },
      },
      {
        id: "Baichuan3-Turbo",
        name: "Baichuan 3 Turbo",
        maxTokens: 32000,
        pricing: { input: 0.008, output: 0.008 },
      },
      {
        id: "Baichuan2-Turbo",
        name: "Baichuan 2 Turbo",
        maxTokens: 32000,
        pricing: { input: 0.004, output: 0.004 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "yi",
    name: "零一万物",
    category: "cloud",
    icon: "1️⃣",
    description: "Yi 系列大模型",
    website: "https://www.lingyiwanwu.com",
    docs: "https://platform.lingyiwanwu.com/docs",
    api: {
      defaultBaseUrl: "https://api.lingyiwanwu.com/v1",
      authType: "bearer",
      apiKeyPlaceholder: "Yi API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "yi-large",
        name: "Yi Large",
        maxTokens: 32768,
        pricing: { input: 0.015, output: 0.015 },
      },
      {
        id: "yi-medium",
        name: "Yi Medium",
        maxTokens: 16384,
        pricing: { input: 0.0025, output: 0.0025 },
      },
      {
        id: "yi-spark",
        name: "Yi Spark",
        maxTokens: 16384,
        pricing: { input: 0.0006, output: 0.0006 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "sensetime",
    name: "商汤科技",
    category: "cloud",
    icon: "🖼️",
    description: "日日新大模型",
    website: "https://www.sensetime.com",
    docs: "https://platform.sensenova.cn/docs",
    api: {
      defaultBaseUrl: "https://api.sensenova.cn/v1",
      authType: "bearer",
      apiKeyPlaceholder: "商汤 API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "nova-ptc-xl-v1",
        name: "日日新 PTC XL",
        maxTokens: 128000,
        pricing: { input: 0.06, output: 0.06 },
      },
      {
        id: "nova-ptc-s-v1",
        name: "日日新 PTC S",
        maxTokens: 8000,
        pricing: { input: 0.002, output: 0.002 },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "iflytek",
    name: "科大讯飞",
    category: "cloud",
    icon: "🎙️",
    description: "讯飞星火大模型",
    website: "https://www.xfyun.cn",
    docs: "https://www.xfyun.cn/doc",
    api: {
      defaultBaseUrl: "https://spark-api-open.xf-yun.com/v1",
      authType: "bearer",
      apiKeyPlaceholder: "讯飞 API Key",
    },
    configFields: [
      {
        key: "apiSecret",
        label: "API Secret",
        type: "password",
        required: true,
      },
    ],
    defaultModels: [
      {
        id: "generalv3.5",
        name: "星火 3.5",
        maxTokens: 8192,
        pricing: { input: 0.003, output: 0.003 },
      },
      {
        id: "generalv3",
        name: "星火 3.0",
        maxTokens: 8192,
        pricing: { input: 0.002, output: 0.002 },
      },
      {
        id: "generalv2",
        name: "星火 2.0",
        maxTokens: 4096,
        pricing: { input: 0.001, output: 0.001 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "stepfun",
    name: "阶跃星辰",
    category: "cloud",
    icon: "🚶",
    description: "Step 系列大模型",
    website: "https://www.stepfun.com",
    docs: "https://www.stepfun.com/docs",
    api: {
      defaultBaseUrl: "https://api.stepfun.com/v1",
      authType: "bearer",
      apiKeyPlaceholder: "Step API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "step-1-8k",
        name: "Step 1 8K",
        maxTokens: 8192,
        pricing: { input: 0.005, output: 0.02 },
      },
      {
        id: "step-1-32k",
        name: "Step 1 32K",
        maxTokens: 32768,
        pricing: { input: 0.015, output: 0.07 },
      },
      {
        id: "step-1-128k",
        name: "Step 1 128K",
        maxTokens: 131072,
        pricing: { input: 0.04, output: 0.12 },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "kuaishou",
    name: "快手大模型",
    category: "cloud",
    icon: "⚡",
    description: "快手 KwYii 模型",
    website: "https://www.kuaishou.com",
    docs: "https://www.kuaishou.com/developer",
    api: {
      defaultBaseUrl: "https://api.kuaishou.com/v1",
      authType: "bearer",
      apiKeyPlaceholder: "快手 API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "kwyi-large",
        name: "KwYii Large",
        maxTokens: 8192,
        pricing: { input: 0.003, output: 0.003 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "modelscope",
    name: "ModelScope",
    category: "cloud",
    icon: "🔬",
    description: "阿里达摩院魔搭社区",
    website: "https://www.modelscope.cn",
    docs: "https://www.modelscope.cn/docs",
    api: {
      defaultBaseUrl: "https://api-inference.modelscope.cn/v1",
      authType: "bearer",
      apiKeyPlaceholder: "ModelScope API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "qwen-turbo",
        name: "Qwen Turbo",
        maxTokens: 8192,
        pricing: { input: 0.0003, output: 0.0006 },
      },
      {
        id: "chatglm3-6b",
        name: "ChatGLM3 6B",
        maxTokens: 8192,
        pricing: { input: 0, output: 0 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: false,
    },
  },
  // ==================== 国际厂商 ====================
  {
    type: "openai",
    name: "OpenAI",
    category: "cloud",
    icon: "🤖",
    description: "GPT-4、GPT-4 Turbo、GPT-3.5 等主流大模型",
    website: "https://openai.com",
    docs: "https://platform.openai.com/docs",
    api: {
      defaultBaseUrl: "https://api.openai.com/v1",
      authType: "bearer",
      apiKeyPrefix: "sk-",
      apiKeyPlaceholder: "sk-...",
    },
    configFields: [
      {
        key: "organization",
        label: "Organization ID",
        type: "text",
        placeholder: "org-...",
        description: "可选，用于组织计费",
      },
    ],
    defaultModels: [
      {
        id: "gpt-4o",
        name: "GPT-4o",
        maxTokens: 128000,
        pricing: { input: 0.005, output: 0.015 },
        capabilities: { vision: true, streaming: true, functionCalling: true },
      },
      {
        id: "gpt-4-turbo",
        name: "GPT-4 Turbo",
        maxTokens: 128000,
        pricing: { input: 0.01, output: 0.03 },
        capabilities: { vision: true, streaming: true, functionCalling: true },
      },
      {
        id: "gpt-4",
        name: "GPT-4",
        maxTokens: 8192,
        pricing: { input: 0.03, output: 0.06 },
        capabilities: { streaming: true, functionCalling: true },
      },
      {
        id: "gpt-3.5-turbo",
        name: "GPT-3.5 Turbo",
        maxTokens: 16384,
        pricing: { input: 0.0005, output: 0.0015 },
        capabilities: { streaming: true, functionCalling: true },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "anthropic",
    name: "Anthropic",
    category: "cloud",
    icon: "🧠",
    description: "Claude 3 系列模型，擅长长文本和复杂推理",
    website: "https://anthropic.com",
    docs: "https://docs.anthropic.com",
    api: {
      defaultBaseUrl: "https://api.anthropic.com/v1",
      authType: "bearer",
      apiKeyPrefix: "sk-ant-",
      apiKeyPlaceholder: "sk-ant-...",
      headers: { "anthropic-version": "2023-06-01" },
    },
    configFields: [],
    defaultModels: [
      {
        id: "claude-3-5-sonnet-20241022",
        name: "Claude 3.5 Sonnet",
        maxTokens: 200000,
        pricing: { input: 0.003, output: 0.015 },
        capabilities: { vision: true, streaming: true, functionCalling: true },
      },
      {
        id: "claude-3-opus-20240229",
        name: "Claude 3 Opus",
        maxTokens: 200000,
        pricing: { input: 0.015, output: 0.075 },
        capabilities: { vision: true, streaming: true, functionCalling: true },
      },
      {
        id: "claude-3-haiku-20240307",
        name: "Claude 3 Haiku",
        maxTokens: 200000,
        pricing: { input: 0.00025, output: 0.00125 },
        capabilities: { vision: true, streaming: true, functionCalling: true },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "google",
    name: "Google AI",
    category: "cloud",
    icon: "🔷",
    description: "Gemini 系列模型，支持多模态和长上下文",
    website: "https://ai.google.dev",
    docs: "https://ai.google.dev/docs",
    api: {
      defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta",
      authType: "api_key",
      apiKeyPlaceholder: "AIza...",
    },
    configFields: [],
    defaultModels: [
      {
        id: "gemini-1.5-pro",
        name: "Gemini 1.5 Pro",
        maxTokens: 1000000,
        pricing: { input: 0.00125, output: 0.005 },
        capabilities: { vision: true, streaming: true, functionCalling: true },
      },
      {
        id: "gemini-1.5-flash",
        name: "Gemini 1.5 Flash",
        maxTokens: 1000000,
        pricing: { input: 0.000075, output: 0.0003 },
        capabilities: { vision: true, streaming: true, functionCalling: true },
      },
      {
        id: "gemini-pro",
        name: "Gemini Pro",
        maxTokens: 32760,
        pricing: { input: 0.00025, output: 0.0005 },
        capabilities: { vision: true, streaming: true, functionCalling: true },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: true,
      jsonMode: true,
    },
  },
  {
    type: "azure",
    name: "Azure OpenAI",
    category: "cloud",
    icon: "☁️",
    description: "微软 Azure 托管的 OpenAI 模型服务",
    website: "https://azure.microsoft.com/openai",
    docs: "https://learn.microsoft.com/azure/ai-services/openai",
    api: {
      defaultBaseUrl: "https://YOUR_RESOURCE.openai.azure.com",
      authType: "api_key",
      apiKeyPlaceholder: "Azure API Key",
    },
    configFields: [
      {
        key: "deploymentName",
        label: "Deployment Name",
        type: "text",
        placeholder: "gpt-4",
        required: true,
        description: "Azure 中部署的模型名称",
      },
      {
        key: "apiVersion",
        label: "API Version",
        type: "text",
        defaultValue: "2024-02-15-preview",
        description: "Azure OpenAI API 版本",
      },
    ],
    defaultModels: [
      {
        id: "gpt-4o",
        name: "GPT-4o",
        maxTokens: 128000,
        pricing: { input: 0.005, output: 0.015 },
      },
      {
        id: "gpt-4",
        name: "GPT-4",
        maxTokens: 8192,
        pricing: { input: 0.03, output: 0.06 },
      },
      {
        id: "gpt-35-turbo",
        name: "GPT-3.5 Turbo",
        maxTokens: 16384,
        pricing: { input: 0.0005, output: 0.0015 },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "aws_bedrock",
    name: "AWS Bedrock",
    category: "cloud",
    icon: "🚀",
    description: "亚马逊 Bedrock 托管多种基础模型",
    website: "https://aws.amazon.com/bedrock",
    docs: "https://docs.aws.amazon.com/bedrock",
    api: {
      defaultBaseUrl: "https://bedrock-runtime.{region}.amazonaws.com",
      authType: "basic",
    },
    configFields: [
      {
        key: "region",
        label: "AWS Region",
        type: "select",
        defaultValue: "us-east-1",
        required: true,
        options: [
          { label: "US East (N. Virginia)", value: "us-east-1" },
          { label: "US West (Oregon)", value: "us-west-2" },
          { label: "Europe (Frankfurt)", value: "eu-central-1" },
          { label: "Asia Pacific (Singapore)", value: "ap-southeast-1" },
          { label: "Asia Pacific (Tokyo)", value: "ap-northeast-1" },
        ],
      },
      {
        key: "accessKeyId",
        label: "Access Key ID",
        type: "text",
        required: true,
      },
      {
        key: "secretAccessKey",
        label: "Secret Access Key",
        type: "password",
        required: true,
      },
    ],
    defaultModels: [
      {
        id: "anthropic.claude-3-sonnet",
        name: "Claude 3 Sonnet",
        maxTokens: 200000,
        pricing: { input: 0.003, output: 0.015 },
      },
      {
        id: "anthropic.claude-3-haiku",
        name: "Claude 3 Haiku",
        maxTokens: 200000,
        pricing: { input: 0.00025, output: 0.00125 },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "mistral",
    name: "Mistral AI",
    category: "cloud",
    icon: "🌀",
    description: "Mistral 开源和商业模型",
    website: "https://mistral.ai",
    docs: "https://docs.mistral.ai",
    api: {
      defaultBaseUrl: "https://api.mistral.ai/v1",
      authType: "bearer",
      apiKeyPlaceholder: "Mistral API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "mistral-large-latest",
        name: "Mistral Large",
        maxTokens: 128000,
        pricing: { input: 0.004, output: 0.012 },
      },
      {
        id: "mistral-medium-latest",
        name: "Mistral Medium",
        maxTokens: 32000,
        pricing: { input: 0.0027, output: 0.0081 },
      },
      {
        id: "open-mixtral-8x22b",
        name: "Mixtral 8x22B",
        maxTokens: 65536,
        pricing: { input: 0.00065, output: 0.00065 },
      },
      {
        id: "open-mistral-7b",
        name: "Mistral 7B",
        maxTokens: 32000,
        pricing: { input: 0.00025, output: 0.00025 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "cohere",
    name: "Cohere",
    category: "cloud",
    icon: "🔵",
    description: "Cohere 企业级语言模型",
    website: "https://cohere.com",
    docs: "https://docs.cohere.com",
    api: {
      defaultBaseUrl: "https://api.cohere.ai/v1",
      authType: "bearer",
      apiKeyPlaceholder: "Cohere API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "command-r-plus",
        name: "Command R+",
        maxTokens: 128000,
        pricing: { input: 0.003, output: 0.015 },
      },
      {
        id: "command-r",
        name: "Command R",
        maxTokens: 128000,
        pricing: { input: 0.0005, output: 0.0015 },
      },
      {
        id: "command",
        name: "Command",
        maxTokens: 4096,
        pricing: { input: 0.001, output: 0.002 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "deepseek",
    name: "DeepSeek",
    category: "cloud",
    icon: "🔍",
    description: "DeepSeek 深度求索大模型",
    website: "https://deepseek.com",
    docs: "https://platform.deepseek.com/docs",
    api: {
      defaultBaseUrl: "https://api.deepseek.com/v1",
      authType: "bearer",
      apiKeyPrefix: "sk-",
      apiKeyPlaceholder: "sk-...",
    },
    configFields: [],
    defaultModels: [
      {
        id: "deepseek-chat",
        name: "DeepSeek Chat",
        maxTokens: 64000,
        pricing: { input: 0.0001, output: 0.0002 },
      },
      {
        id: "deepseek-coder",
        name: "DeepSeek Coder",
        maxTokens: 64000,
        pricing: { input: 0.0001, output: 0.0002 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "groq",
    name: "Groq",
    category: "cloud",
    icon: "⚡",
    description: "Groq LPU 推理引擎，极速响应",
    website: "https://groq.com",
    docs: "https://console.groq.com/docs",
    api: {
      defaultBaseUrl: "https://api.groq.com/openai/v1",
      authType: "bearer",
      apiKeyPrefix: "gsk_",
      apiKeyPlaceholder: "gsk_...",
    },
    configFields: [],
    defaultModels: [
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B",
        maxTokens: 128000,
        pricing: { input: 0.00059, output: 0.00079 },
      },
      {
        id: "llama-3.1-8b-instant",
        name: "Llama 3.1 8B",
        maxTokens: 128000,
        pricing: { input: 0.00002, output: 0.00002 },
      },
      {
        id: "mixtral-8x7b-32768",
        name: "Mixtral 8x7B",
        maxTokens: 32768,
        pricing: { input: 0.00027, output: 0.00027 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "perplexity",
    name: "Perplexity",
    category: "cloud",
    icon: "🔮",
    description: "Perplexity AI 搜索增强模型",
    website: "https://perplexity.ai",
    docs: "https://docs.perplexity.ai",
    api: {
      defaultBaseUrl: "https://api.perplexity.ai",
      authType: "bearer",
      apiKeyPrefix: "pplx-",
      apiKeyPlaceholder: "pplx-...",
    },
    configFields: [],
    defaultModels: [
      {
        id: "llama-3.1-sonar-large-128k-online",
        name: "Sonar Large Online",
        maxTokens: 127072,
        pricing: { input: 0.001, output: 0.001 },
      },
      {
        id: "llama-3.1-sonar-small-128k-online",
        name: "Sonar Small Online",
        maxTokens: 127072,
        pricing: { input: 0.0002, output: 0.0002 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: false,
    },
  },
  {
    type: "together",
    name: "Together AI",
    category: "cloud",
    icon: "🤝",
    description: "Together AI 托管开源模型",
    website: "https://together.ai",
    docs: "https://docs.together.ai",
    api: {
      defaultBaseUrl: "https://api.together.xyz/v1",
      authType: "bearer",
      apiKeyPlaceholder: "Together API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "meta-llama/Llama-3-70b-chat-hf",
        name: "Llama 3 70B",
        maxTokens: 8192,
        pricing: { input: 0.0008, output: 0.0008 },
      },
      {
        id: "mistralai/Mixtral-8x7B-Instruct-v0.1",
        name: "Mixtral 8x7B",
        maxTokens: 32768,
        pricing: { input: 0.0006, output: 0.0006 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "huggingface",
    name: "Hugging Face",
    category: "cloud",
    icon: "🤗",
    description: "Hugging Face Inference API",
    website: "https://huggingface.co",
    docs: "https://huggingface.co/docs/api-inference",
    api: {
      defaultBaseUrl: "https://api-inference.huggingface.co/models",
      authType: "bearer",
      apiKeyPrefix: "hf_",
      apiKeyPlaceholder: "hf_...",
    },
    configFields: [
      {
        key: "modelId",
        label: "Model ID",
        type: "text",
        placeholder: "meta-llama/Llama-2-70b-chat-hf",
        required: true,
        description: "Hugging Face 模型 ID",
      },
    ],
    defaultModels: [
      {
        id: "meta-llama/Llama-2-70b-chat-hf",
        name: "Llama 2 70B",
        maxTokens: 4096,
        pricing: { input: 0, output: 0 },
      },
      {
        id: "mistralai/Mistral-7B-Instruct-v0.2",
        name: "Mistral 7B",
        maxTokens: 32768,
        pricing: { input: 0, output: 0 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: false,
    },
  },
  {
    type: "replicate",
    name: "Replicate",
    category: "cloud",
    icon: "🔄",
    description: "Replicate 云端模型推理",
    website: "https://replicate.com",
    docs: "https://replicate.com/docs",
    api: {
      defaultBaseUrl: "https://api.replicate.com/v1",
      authType: "bearer",
      apiKeyPrefix: "r8_",
      apiKeyPlaceholder: "r8_...",
    },
    configFields: [],
    defaultModels: [
      {
        id: "meta/llama-2-70b-chat",
        name: "Llama 2 70B",
        maxTokens: 4096,
        pricing: { input: 0.001, output: 0.001 },
      },
      {
        id: "mistralai/mistral-7b-instruct-v0.2",
        name: "Mistral 7B",
        maxTokens: 32768,
        pricing: { input: 0.0001, output: 0.0001 },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: false,
    },
  },
  {
    type: "nvidia",
    name: "NVIDIA NIM",
    category: "cloud",
    icon: "💚",
    description: "NVIDIA NIM 推理微服务",
    website: "https://build.nvidia.com",
    docs: "https://docs.nvidia.com/nim",
    api: {
      defaultBaseUrl: "https://integrate.api.nvidia.com/v1",
      authType: "bearer",
      apiKeyPlaceholder: "NVIDIA API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "meta/llama-3.1-405b-instruct",
        name: "Llama 3.1 405B",
        maxTokens: 128000,
        pricing: { input: 0.003, output: 0.003 },
      },
      {
        id: "meta/llama-3.1-70b-instruct",
        name: "Llama 3.1 70B",
        maxTokens: 128000,
        pricing: { input: 0.0007, output: 0.0007 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "ai21",
    name: "AI21 Labs",
    category: "cloud",
    icon: "✨",
    description: "AI21 Jurassic 模型",
    website: "https://ai21.com",
    docs: "https://docs.ai21.com",
    api: {
      defaultBaseUrl: "https://api.ai21.com/studio/v1",
      authType: "bearer",
      apiKeyPlaceholder: "AI21 API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "jamba-1-5-large",
        name: "Jamba 1.5 Large",
        maxTokens: 256000,
        pricing: { input: 0.002, output: 0.008 },
      },
      {
        id: "jamba-1-5-mini",
        name: "Jamba 1.5 Mini",
        maxTokens: 256000,
        pricing: { input: 0.0002, output: 0.0004 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "grok",
    name: "Grok (xAI)",
    category: "cloud",
    icon: "👽",
    description: "xAI Grok 模型",
    website: "https://x.ai",
    docs: "https://docs.x.ai",
    api: {
      defaultBaseUrl: "https://api.x.ai/v1",
      authType: "bearer",
      apiKeyPlaceholder: "xAI API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "grok-beta",
        name: "Grok Beta",
        maxTokens: 131072,
        pricing: { input: 0.005, output: 0.015 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "cognition",
    name: "Cognition",
    category: "cloud",
    icon: "🧩",
    description: "Cognition Devin/Devin-2 模型",
    website: "https://cognition.ai",
    docs: "https://docs.cognition.ai",
    api: {
      defaultBaseUrl: "https://api.cognition.ai/v1",
      authType: "bearer",
      apiKeyPlaceholder: "Cognition API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "devin-2",
        name: "Devin 2",
        maxTokens: 128000,
        pricing: { input: 0.01, output: 0.03 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: true,
      jsonMode: true,
    },
  },
  {
    type: "meta",
    name: "Meta AI",
    category: "cloud",
    icon: "📘",
    description: "Meta Llama 开源模型系列",
    website: "https://llama.meta.com",
    docs: "https://llama.meta.com/docs",
    api: {
      defaultBaseUrl: "https://api.meta.ai/v1",
      authType: "bearer",
      apiKeyPlaceholder: "Meta API Key",
    },
    configFields: [],
    defaultModels: [
      {
        id: "llama-3.3-70b",
        name: "Llama 3.3 70B",
        maxTokens: 128000,
        pricing: { input: 0, output: 0 },
      },
      {
        id: "llama-3.2-90b",
        name: "Llama 3.2 90B",
        maxTokens: 128000,
        pricing: { input: 0, output: 0 },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
];

// ==================== 开源/本地配置 ====================

const opensourceProviders: ProviderConfig[] = [
  {
    type: "ollama",
    name: "Ollama",
    category: "opensource",
    icon: "🦙",
    description: "本地运行开源大模型",
    website: "https://ollama.ai",
    docs: "https://github.com/ollama/ollama",
    api: {
      defaultBaseUrl: "http://localhost:11434/v1",
      authType: "none",
    },
    configFields: [],
    defaultModels: [
      {
        id: "llama3.3",
        name: "Llama 3.3 70B",
        maxTokens: 128000,
        pricing: { input: 0, output: 0 },
      },
      {
        id: "llama3.2",
        name: "Llama 3.2 3B",
        maxTokens: 128000,
        pricing: { input: 0, output: 0 },
      },
      {
        id: "mistral",
        name: "Mistral 7B",
        maxTokens: 32768,
        pricing: { input: 0, output: 0 },
      },
      {
        id: "qwen2.5",
        name: "Qwen 2.5",
        maxTokens: 32768,
        pricing: { input: 0, output: 0 },
      },
      {
        id: "deepseek-coder-v2",
        name: "DeepSeek Coder V2",
        maxTokens: 32768,
        pricing: { input: 0, output: 0 },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "vllm",
    name: "vLLM",
    category: "opensource",
    icon: "⚡",
    description: "高性能 LLM 推理引擎",
    website: "https://vllm.readthedocs.io",
    docs: "https://vllm.readthedocs.io/en/latest",
    api: {
      defaultBaseUrl: "http://localhost:8000/v1",
      authType: "none",
    },
    configFields: [],
    defaultModels: [
      {
        id: "custom-model",
        name: "Custom Model",
        maxTokens: 4096,
        pricing: { input: 0, output: 0 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "lmstudio",
    name: "LM Studio",
    category: "opensource",
    icon: "🏠",
    description: "本地模型运行和管理",
    website: "https://lmstudio.ai",
    docs: "https://lmstudio.ai/docs",
    api: {
      defaultBaseUrl: "http://localhost:1234/v1",
      authType: "none",
    },
    configFields: [],
    defaultModels: [
      {
        id: "local-model",
        name: "Local Model",
        maxTokens: 4096,
        pricing: { input: 0, output: 0 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "localai",
    name: "LocalAI",
    category: "opensource",
    icon: "🖥️",
    description: "自托管 OpenAI 兼容 API",
    website: "https://localai.io",
    docs: "https://localai.io/basics/getting_started",
    api: {
      defaultBaseUrl: "http://localhost:8080/v1",
      authType: "none",
    },
    configFields: [],
    defaultModels: [
      {
        id: "local-model",
        name: "Local Model",
        maxTokens: 4096,
        pricing: { input: 0, output: 0 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "textgen",
    name: "Text Generation WebUI",
    category: "opensource",
    icon: "💬",
    description: "Oobabooga 文本生成 Web UI",
    website: "https://github.com/oobabooga/text-generation-webui",
    docs: "https://github.com/oobabooga/text-generation-webui/wiki",
    api: {
      defaultBaseUrl: "http://localhost:5000/v1",
      authType: "none",
    },
    configFields: [],
    defaultModels: [
      {
        id: "local-model",
        name: "Local Model",
        maxTokens: 4096,
        pricing: { input: 0, output: 0 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: false,
    },
  },
  {
    type: "openrouter",
    name: "OpenRouter",
    category: "opensource",
    icon: "🔀",
    description: "统一 API 访问多种模型",
    website: "https://openrouter.ai",
    docs: "https://openrouter.ai/docs",
    api: {
      defaultBaseUrl: "https://openrouter.ai/api/v1",
      authType: "bearer",
      apiKeyPrefix: "sk-or-",
      apiKeyPlaceholder: "sk-or-...",
    },
    configFields: [
      {
        key: "siteUrl",
        label: "Site URL",
        type: "url",
        placeholder: "https://your-site.com",
        description: "可选，用于排名",
      },
    ],
    defaultModels: [
      {
        id: "openai/gpt-4o",
        name: "GPT-4o",
        maxTokens: 128000,
        pricing: { input: 0.005, output: 0.015 },
      },
      {
        id: "anthropic/claude-3.5-sonnet",
        name: "Claude 3.5 Sonnet",
        maxTokens: 200000,
        pricing: { input: 0.003, output: 0.015 },
      },
      {
        id: "meta-llama/llama-3.1-70b-instruct",
        name: "Llama 3.1 70B",
        maxTokens: 128000,
        pricing: { input: 0.0003, output: 0.0003 },
      },
    ],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
];

// ==================== 自定义配置 ====================

const customProviders: ProviderConfig[] = [
  {
    type: "custom",
    name: "自定义 Provider",
    category: "custom",
    icon: "⚙️",
    description: "自定义 OpenAI 兼容 API",
    website: "",
    docs: "",
    api: {
      defaultBaseUrl: "",
      authType: "bearer",
      apiKeyPlaceholder: "API Key",
    },
    configFields: [
      {
        key: "baseUrl",
        label: "Base URL",
        type: "url",
        placeholder: "https://api.example.com/v1",
        required: true,
        description: "API 基础地址",
      },
      {
        key: "modelName",
        label: "Model Name",
        type: "text",
        placeholder: "gpt-4",
        required: true,
        description: "模型名称",
      },
    ],
    defaultModels: [
      {
        id: "custom-model",
        name: "Custom Model",
        maxTokens: 4096,
        pricing: { input: 0, output: 0 },
      },
    ],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: true,
    },
  },
];

// ==================== 导出配置 ====================

// 所有厂商配置
export const allProviderConfigs: ProviderConfig[] = [
  ...cloudProviders,
  ...opensourceProviders,
  ...customProviders,
];

// 按分类获取配置
export const getProvidersByCategory = (
  category: ProviderCategory,
): ProviderConfig[] => {
  return allProviderConfigs.filter((config) => config.category === category);
};

// 根据 ProviderType 获取配置
export const getProviderConfig = (
  type: ProviderType,
): ProviderConfig | undefined => {
  return allProviderConfigs.find((config) => config.type === type);
};

// 分类信息
export const categoryInfo: Record<
  ProviderCategory,
  { name: string; description: string }
> = {
  cloud: {
    name: "云服务商",
    description: "OpenAI、Anthropic、硅基流动、智谱等主流云服务商",
  },
  opensource: { name: "开源/本地", description: "Ollama、vLLM 等本地部署方案" },
  custom: { name: "自定义", description: "自定义 OpenAI 兼容 API" },
};

// 获取厂商简单配置（用于列表显示）
export const getProviderTypeConfig = (
  type: ProviderType,
): { name: string; color: string; icon: string } => {
  const config = getProviderConfig(type);
  if (!config) {
    return { name: type, color: "default", icon: "⚙️" };
  }

  const colorMap: Record<ProviderCategory, string> = {
    cloud: "blue",
    opensource: "purple",
    custom: "default",
  };

  return {
    name: config.name,
    color: colorMap[config.category],
    icon: config.icon,
  };
};

export default allProviderConfigs;
