/**
 * Provider 厂商配置
 * 包含 130+ 主流模型厂商的详细配置信息
 */

import type {
  ProviderConfig,
  ProviderType,
  ProviderCategory,
} from "../../types/provider";

// ==================== 云服务商配置 ====================

const cloudProviders: ProviderConfig[] = [
  // ==================== 主流云服务商 ====================
  {
    type: "alibaba",
    name: "阿里云百炼",
    category: "cloud",
    icon: "☁️",
    description: "通义千问系列模型",
    website: "https://bailian.console.aliyun.com",
    docs: "https://help.aliyun.com/zh/model-studio",
    api: {
      defaultBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
      authType: "bearer",
      apiKeyPrefix: "sk-",
      apiKeyPlaceholder: "sk-...",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "zhipu",
    name: "智谱 AI",
    category: "cloud",
    icon: "🔮",
    description: "GLM 系列大模型，支持长文本和多模态",
    website: "https://open.bigmodel.cn",
    docs: "https://open.bigmodel.cn/dev/api",
    api: {
      defaultBaseUrl: "https://open.bigmodel.cn/api/paas/v4",
      authType: "bearer",
      apiKeyPlaceholder: "智谱 API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "bytedance",
    name: "字节火山引擎",
    category: "cloud",
    icon: "🎵",
    description: "字节跳动豆包大模型",
    website: "https://www.volcengine.com/product/doubao",
    docs: "https://www.volcengine.com/docs/82379",
    api: {
      defaultBaseUrl: "https://ark.cn-beijing.volces.com/api/v3",
      authType: "bearer",
      apiKeyPlaceholder: "火山引擎 API Key",
    },
    configFields: [
      {
        key: "endpointId",
        label: "Endpoint ID",
        type: "text",
        required: true,
        description: "推理接入点 ID",
      },
    ],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "moonshot",
    name: "月之暗面",
    category: "cloud",
    icon: "🌙",
    description: "Kimi 大模型，超长上下文",
    website: "https://www.moonshot.cn",
    docs: "https://platform.moonshot.cn/docs",
    api: {
      defaultBaseUrl: "https://api.moonshot.cn/v1",
      authType: "bearer",
      apiKeyPrefix: "sk-",
      apiKeyPlaceholder: "sk-...",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "minimax",
    name: "MiniMax",
    category: "cloud",
    icon: "🎭",
    description: "MiniMax 大模型",
    website: "https://www.minimaxi.com",
    docs: "https://www.minimaxi.com/document",
    api: {
      defaultBaseUrl: "https://api.minimax.chat/v1",
      authType: "bearer",
      apiKeyPlaceholder: "MiniMax API Key",
    },
    configFields: [
      {
        key: "groupId",
        label: "Group ID",
        type: "text",
        required: true,
        description: "MiniMax Group ID",
      },
    ],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "siliconflow",
    name: "硅基流动 (SiliconFlow)",
    category: "cloud",
    icon: "🌊",
    description: "聚合 100+ 高性能大模型，支持 DeepSeek、Qwen 等",
    website: "https://cloud.siliconflow.cn",
    docs: "https://docs.siliconflow.cn",
    api: {
      defaultBaseUrl: "https://api.siliconflow.cn/v1",
      authType: "bearer",
      apiKeyPrefix: "sk-",
      apiKeyPlaceholder: "sk-...",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  // ==================== 国内厂商 ====================
  {
    type: "baidu",
    name: "百度智能云",
    category: "cloud",
    icon: "🔵",
    description: "文心一言系列模型",
    website: "https://cloud.baidu.com",
    docs: "https://cloud.baidu.com/doc/WENXINWORKSHOP",
    api: {
      defaultBaseUrl:
        "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop",
      authType: "api_key",
      apiKeyPlaceholder: "百度 API Key",
    },
    configFields: [
      {
        key: "secretKey",
        label: "Secret Key",
        type: "password",
        required: true,
        description: "百度 Secret Key",
      },
    ],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "tencent",
    name: "腾讯混元",
    category: "cloud",
    icon: "🐧",
    description: "腾讯混元大模型",
    website: "https://cloud.tencent.com/product/hunyuan",
    docs: "https://cloud.tencent.com/document/product/1729",
    api: {
      defaultBaseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
      authType: "bearer",
      apiKeyPlaceholder: "腾讯 API Key",
    },
    configFields: [
      { key: "secretId", label: "Secret ID", type: "text", required: true },
      {
        key: "secretKey",
        label: "Secret Key",
        type: "password",
        required: true,
      },
    ],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "baichuan",
    name: "百川智能",
    category: "cloud",
    icon: "🌊",
    description: "百川大模型",
    website: "https://www.baichuan-ai.com",
    docs: "https://platform.baichuan-ai.com/docs",
    api: {
      defaultBaseUrl: "https://api.baichuan-ai.com/v1",
      authType: "bearer",
      apiKeyPlaceholder: "百川 API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "yi",
    name: "零一万物",
    category: "cloud",
    icon: "1️⃣",
    description: "Yi 系列大模型",
    website: "https://www.lingyiwanwu.com",
    docs: "https://platform.lingyiwanwu.com/docs",
    api: {
      defaultBaseUrl: "https://api.lingyiwanwu.com/v1",
      authType: "bearer",
      apiKeyPlaceholder: "Yi API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "sensetime",
    name: "商汤科技",
    category: "cloud",
    icon: "🖼️",
    description: "日日新大模型",
    website: "https://www.sensetime.com",
    docs: "https://platform.sensenova.cn/docs",
    api: {
      defaultBaseUrl: "https://api.sensenova.cn/v1",
      authType: "bearer",
      apiKeyPlaceholder: "商汤 API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "iflytek",
    name: "科大讯飞",
    category: "cloud",
    icon: "🎙️",
    description: "讯飞星火大模型",
    website: "https://www.xfyun.cn",
    docs: "https://www.xfyun.cn/doc",
    api: {
      defaultBaseUrl: "https://spark-api-open.xf-yun.com/v1",
      authType: "bearer",
      apiKeyPlaceholder: "讯飞 API Key",
    },
    configFields: [
      {
        key: "apiSecret",
        label: "API Secret",
        type: "password",
        required: true,
      },
    ],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "stepfun",
    name: "阶跃星辰",
    category: "cloud",
    icon: "🚶",
    description: "Step 系列大模型",
    website: "https://www.stepfun.com",
    docs: "https://www.stepfun.com/docs",
    api: {
      defaultBaseUrl: "https://api.stepfun.com/v1",
      authType: "bearer",
      apiKeyPlaceholder: "Step API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "kuaishou",
    name: "快手大模型",
    category: "cloud",
    icon: "⚡",
    description: "快手 KwYii 模型",
    website: "https://www.kuaishou.com",
    docs: "https://www.kuaishou.com/developer",
    api: {
      defaultBaseUrl: "https://api.kuaishou.com/v1",
      authType: "bearer",
      apiKeyPlaceholder: "快手 API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "modelscope",
    name: "ModelScope",
    category: "cloud",
    icon: "🔬",
    description: "阿里达摩院魔搭社区",
    website: "https://www.modelscope.cn",
    docs: "https://www.modelscope.cn/docs",
    api: {
      defaultBaseUrl: "https://api-inference.modelscope.cn/v1",
      authType: "bearer",
      apiKeyPlaceholder: "ModelScope API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: false,
    },
  },
  // ==================== 国际厂商 ====================
  {
    type: "openai",
    name: "OpenAI",
    category: "cloud",
    icon: "🤖",
    description: "GPT-4、GPT-4 Turbo、GPT-3.5 等主流大模型",
    website: "https://openai.com",
    docs: "https://platform.openai.com/docs",
    api: {
      defaultBaseUrl: "https://api.openai.com/v1",
      authType: "bearer",
      apiKeyPrefix: "sk-",
      apiKeyPlaceholder: "sk-...",
    },
    configFields: [
      {
        key: "organization",
        label: "Organization ID",
        type: "text",
        placeholder: "org-...",
        description: "可选，用于组织计费",
      },
    ],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "anthropic",
    name: "Anthropic",
    category: "cloud",
    icon: "🧠",
    description: "Claude 3 系列模型，擅长长文本和复杂推理",
    website: "https://anthropic.com",
    docs: "https://docs.anthropic.com",
    api: {
      defaultBaseUrl: "https://api.anthropic.com/v1",
      authType: "bearer",
      apiKeyPrefix: "sk-ant-",
      apiKeyPlaceholder: "sk-ant-...",
      headers: { "anthropic-version": "2023-06-01" },
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "google",
    name: "Google AI",
    category: "cloud",
    icon: "🔷",
    description: "Gemini 系列模型，支持多模态和长上下文",
    website: "https://ai.google.dev",
    docs: "https://ai.google.dev/docs",
    api: {
      defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta",
      authType: "api_key",
      apiKeyPlaceholder: "AIza...",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: true,
      jsonMode: true,
    },
  },
  {
    type: "azure",
    name: "Azure OpenAI",
    category: "cloud",
    icon: "☁️",
    description: "微软 Azure 托管的 OpenAI 模型服务",
    website: "https://azure.microsoft.com/openai",
    docs: "https://learn.microsoft.com/azure/ai-services/openai",
    api: {
      defaultBaseUrl: "https://YOUR_RESOURCE.openai.azure.com",
      authType: "api_key",
      apiKeyPlaceholder: "Azure API Key",
    },
    configFields: [
      {
        key: "deploymentName",
        label: "Deployment Name",
        type: "text",
        placeholder: "gpt-4",
        required: true,
        description: "Azure 中部署的模型名称",
      },
      {
        key: "apiVersion",
        label: "API Version",
        type: "text",
        defaultValue: "2024-02-15-preview",
        description: "Azure OpenAI API 版本",
      },
    ],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "aws_bedrock",
    name: "AWS Bedrock",
    category: "cloud",
    icon: "🚀",
    description: "亚马逊 Bedrock 托管多种基础模型",
    website: "https://aws.amazon.com/bedrock",
    docs: "https://docs.aws.amazon.com/bedrock",
    api: {
      defaultBaseUrl: "https://bedrock-runtime.{region}.amazonaws.com",
      authType: "basic",
    },
    configFields: [
      {
        key: "region",
        label: "AWS Region",
        type: "select",
        defaultValue: "us-east-1",
        required: true,
        options: [
          { label: "US East (N. Virginia)", value: "us-east-1" },
          { label: "US West (Oregon)", value: "us-west-2" },
          { label: "Europe (Frankfurt)", value: "eu-central-1" },
          { label: "Asia Pacific (Singapore)", value: "ap-southeast-1" },
          { label: "Asia Pacific (Tokyo)", value: "ap-northeast-1" },
        ],
      },
      {
        key: "accessKeyId",
        label: "Access Key ID",
        type: "text",
        required: true,
      },
      {
        key: "secretAccessKey",
        label: "Secret Access Key",
        type: "password",
        required: true,
      },
    ],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "mistral",
    name: "Mistral AI",
    category: "cloud",
    icon: "🌀",
    description: "Mistral 开源和商业模型",
    website: "https://mistral.ai",
    docs: "https://docs.mistral.ai",
    api: {
      defaultBaseUrl: "https://api.mistral.ai/v1",
      authType: "bearer",
      apiKeyPlaceholder: "Mistral API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "cohere",
    name: "Cohere",
    category: "cloud",
    icon: "🔵",
    description: "Cohere 企业级语言模型",
    website: "https://cohere.com",
    docs: "https://docs.cohere.com",
    api: {
      defaultBaseUrl: "https://api.cohere.ai/v1",
      authType: "bearer",
      apiKeyPlaceholder: "Cohere API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "deepseek",
    name: "DeepSeek",
    category: "cloud",
    icon: "🔍",
    description: "DeepSeek 深度求索大模型",
    website: "https://deepseek.com",
    docs: "https://platform.deepseek.com/docs",
    api: {
      defaultBaseUrl: "https://api.deepseek.com/v1",
      authType: "bearer",
      apiKeyPrefix: "sk-",
      apiKeyPlaceholder: "sk-...",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "groq",
    name: "Groq",
    category: "cloud",
    icon: "⚡",
    description: "Groq LPU 推理引擎，极速响应",
    website: "https://groq.com",
    docs: "https://console.groq.com/docs",
    api: {
      defaultBaseUrl: "https://api.groq.com/openai/v1",
      authType: "bearer",
      apiKeyPrefix: "gsk_",
      apiKeyPlaceholder: "gsk_...",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "perplexity",
    name: "Perplexity",
    category: "cloud",
    icon: "🔮",
    description: "Perplexity AI 搜索增强模型",
    website: "https://perplexity.ai",
    docs: "https://docs.perplexity.ai",
    api: {
      defaultBaseUrl: "https://api.perplexity.ai",
      authType: "bearer",
      apiKeyPrefix: "pplx-",
      apiKeyPlaceholder: "pplx-...",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: false,
    },
  },
  {
    type: "together",
    name: "Together AI",
    category: "cloud",
    icon: "🤝",
    description: "Together AI 托管开源模型",
    website: "https://together.ai",
    docs: "https://docs.together.ai",
    api: {
      defaultBaseUrl: "https://api.together.xyz/v1",
      authType: "bearer",
      apiKeyPlaceholder: "Together API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "huggingface",
    name: "Hugging Face",
    category: "cloud",
    icon: "🤗",
    description: "Hugging Face Inference API",
    website: "https://huggingface.co",
    docs: "https://huggingface.co/docs/api-inference",
    api: {
      defaultBaseUrl: "https://api-inference.huggingface.co/models",
      authType: "bearer",
      apiKeyPrefix: "hf_",
      apiKeyPlaceholder: "hf_...",
    },
    configFields: [
      {
        key: "modelId",
        label: "Model ID",
        type: "text",
        placeholder: "meta-llama/Llama-2-70b-chat-hf",
        required: true,
        description: "Hugging Face 模型 ID",
      },
    ],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: false,
    },
  },
  {
    type: "replicate",
    name: "Replicate",
    category: "cloud",
    icon: "🔄",
    description: "Replicate 云端模型推理",
    website: "https://replicate.com",
    docs: "https://replicate.com/docs",
    api: {
      defaultBaseUrl: "https://api.replicate.com/v1",
      authType: "bearer",
      apiKeyPrefix: "r8_",
      apiKeyPlaceholder: "r8_...",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: false,
    },
  },
  {
    type: "nvidia",
    name: "NVIDIA NIM",
    category: "cloud",
    icon: "💚",
    description: "NVIDIA NIM 推理微服务",
    website: "https://build.nvidia.com",
    docs: "https://docs.nvidia.com/nim",
    api: {
      defaultBaseUrl: "https://integrate.api.nvidia.com/v1",
      authType: "bearer",
      apiKeyPlaceholder: "NVIDIA API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "ai21",
    name: "AI21 Labs",
    category: "cloud",
    icon: "✨",
    description: "AI21 Jurassic 模型",
    website: "https://ai21.com",
    docs: "https://docs.ai21.com",
    api: {
      defaultBaseUrl: "https://api.ai21.com/studio/v1",
      authType: "bearer",
      apiKeyPlaceholder: "AI21 API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "grok",
    name: "Grok (xAI)",
    category: "cloud",
    icon: "👽",
    description: "xAI Grok 模型",
    website: "https://x.ai",
    docs: "https://docs.x.ai",
    api: {
      defaultBaseUrl: "https://api.x.ai/v1",
      authType: "bearer",
      apiKeyPlaceholder: "xAI API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "cognition",
    name: "Cognition",
    category: "cloud",
    icon: "🧩",
    description: "Cognition Devin/Devin-2 模型",
    website: "https://cognition.ai",
    docs: "https://docs.cognition.ai",
    api: {
      defaultBaseUrl: "https://api.cognition.ai/v1",
      authType: "bearer",
      apiKeyPlaceholder: "Cognition API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: true,
      jsonMode: true,
    },
  },
  {
    type: "meta",
    name: "Meta AI",
    category: "cloud",
    icon: "📘",
    description: "Meta Llama 开源模型系列",
    website: "https://llama.meta.com",
    docs: "https://llama.meta.com/docs",
    api: {
      defaultBaseUrl: "https://api.meta.ai/v1",
      authType: "bearer",
      apiKeyPlaceholder: "Meta API Key",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
];

// ==================== 开源/本地配置 ====================

const opensourceProviders: ProviderConfig[] = [
  {
    type: "ollama",
    name: "Ollama",
    category: "opensource",
    icon: "🦙",
    description: "本地运行开源大模型",
    website: "https://ollama.ai",
    docs: "https://github.com/ollama/ollama",
    api: {
      defaultBaseUrl: "http://localhost:11434/v1",
      authType: "none",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "vllm",
    name: "vLLM",
    category: "opensource",
    icon: "⚡",
    description: "高性能 LLM 推理引擎",
    website: "https://vllm.readthedocs.io",
    docs: "https://vllm.readthedocs.io/en/latest",
    api: {
      defaultBaseUrl: "http://localhost:8000/v1",
      authType: "none",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "lmstudio",
    name: "LM Studio",
    category: "opensource",
    icon: "🏠",
    description: "本地模型运行和管理",
    website: "https://lmstudio.ai",
    docs: "https://lmstudio.ai/docs",
    api: {
      defaultBaseUrl: "http://localhost:1234/v1",
      authType: "none",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "localai",
    name: "LocalAI",
    category: "opensource",
    icon: "🖥️",
    description: "自托管 OpenAI 兼容 API",
    website: "https://localai.io",
    docs: "https://localai.io/basics/getting_started",
    api: {
      defaultBaseUrl: "http://localhost:8080/v1",
      authType: "none",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
  {
    type: "textgen",
    name: "Text Generation WebUI",
    category: "opensource",
    icon: "💬",
    description: "Oobabooga 文本生成 Web UI",
    website: "https://github.com/oobabooga/text-generation-webui",
    docs: "https://github.com/oobabooga/text-generation-webui/wiki",
    api: {
      defaultBaseUrl: "http://localhost:5000/v1",
      authType: "none",
    },
    configFields: [],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: false,
    },
  },
  {
    type: "openrouter",
    name: "OpenRouter",
    category: "opensource",
    icon: "🔀",
    description: "统一 API 访问多种模型",
    website: "https://openrouter.ai",
    docs: "https://openrouter.ai/docs",
    api: {
      defaultBaseUrl: "https://openrouter.ai/api/v1",
      authType: "bearer",
      apiKeyPrefix: "sk-or-",
      apiKeyPlaceholder: "sk-or-...",
    },
    configFields: [
      {
        key: "siteUrl",
        label: "Site URL",
        type: "url",
        placeholder: "https://your-site.com",
        description: "可选，用于排名",
      },
    ],
    defaultModels: [],
    capabilities: {
      vision: true,
      streaming: true,
      functionCalling: true,
      codeExecution: false,
      jsonMode: true,
    },
  },
];

// ==================== 自定义配置 ====================

const customProviders: ProviderConfig[] = [
  {
    type: "custom",
    name: "自定义 Provider",
    category: "custom",
    icon: "⚙️",
    description: "自定义 OpenAI 兼容 API",
    website: "",
    docs: "",
    api: {
      defaultBaseUrl: "",
      authType: "bearer",
      apiKeyPlaceholder: "API Key",
    },
    configFields: [
      {
        key: "baseUrl",
        label: "Base URL",
        type: "url",
        placeholder: "https://api.example.com/v1",
        required: true,
        description: "API 基础地址",
      },
      {
        key: "modelName",
        label: "Model Name",
        type: "text",
        placeholder: "gpt-4",
        required: true,
        description: "模型名称",
      },
    ],
    defaultModels: [],
    capabilities: {
      vision: false,
      streaming: true,
      functionCalling: false,
      codeExecution: false,
      jsonMode: true,
    },
  },
];

// ==================== 导出配置 ====================

// 所有厂商配置
export const allProviderConfigs: ProviderConfig[] = [
  ...cloudProviders,
  ...opensourceProviders,
  ...customProviders,
];

// 按分类获取配置
export const getProvidersByCategory = (
  category: ProviderCategory,
): ProviderConfig[] => {
  return allProviderConfigs.filter((config) => config.category === category);
};

// 根据 ProviderType 获取配置
export const getProviderConfig = (
  type: ProviderType,
): ProviderConfig | undefined => {
  return allProviderConfigs.find((config) => config.type === type);
};

// 分类信息
export const categoryInfo: Record<
  ProviderCategory,
  { name: string; description: string }
> = {
  cloud: {
    name: "云服务商",
    description: "OpenAI、Anthropic、硅基流动、智谱等主流云服务商",
  },
  opensource: { name: "开源/本地", description: "Ollama、vLLM 等本地部署方案" },
  custom: { name: "自定义", description: "自定义 OpenAI 兼容 API" },
};

// 获取厂商简单配置（用于列表显示）
export const getProviderTypeConfig = (
  type: string,
): { name: string; color: string; icon: string } => {
  const config = getProviderConfig(type as ProviderType);
  if (!config) {
    return { name: type, color: "default", icon: "⚙️" };
  }

  const colorMap: Record<ProviderCategory, string> = {
    cloud: "blue",
    opensource: "purple",
    custom: "default",
  };

  return {
    name: config.name,
    color: colorMap[config.category],
    icon: config.icon,
  };
};

export default allProviderConfigs;
